echo ""
echo "You enter the torch-lit room,
As you walk in, the piercing gaze sends shivers down your spine...
what is that?
The torch seems to have 't1' engraved in it...
Meybe there is a chest around...
There are stairs that lead downwards"
echo ""
