echo ""
echo "You walk through the tunnel and end up in a giant room...,
There is an empty chest, with a monster prancing around it...
There is rubble spread across the ground...
Was there a fight in here?"
echo ""
