echo ""
echo "You hopped into the bush...
It is covered in spider silk...
It looks there used to be an item around here...
The only useful thing in this bush is a fang...
maybe you will find something...?"
echo ""
