#!/bin/bash

wepDam=$[RANDOM%40+60]  #damages within a range from min (1) to defined number max (6)
#export wepDam=6 #damages with a flat number
wepName='Lima Gun' #weapon name
weaponDesc='The strongest weapon created by the legendary blacksmith' #weapon's description\
