#!/bin/bash

wepDam=4  #damages within a range from min (1) to defined number max (6)
#export wepDam=6 #damages with a flat number
wepName='Spider Fang' #weapon name
weaponDesc='A very weak weapon dropped on the first floor of the dungeon' #weapon's description\
