#!/bin/bash

export wepDam=%[RANDOM%6+1] #damages within a range from min (1) to defined number max (6)
#export wepDam=6 #damages with a flat number
export wepName='fist' #weapon name
export weaponDesc='' #weapon's description
