echo ""
echo "You hopped into the bush...
It is covered in spider silk...
It looks like there may have been an item around here...
The only useful thing in this bush is a fang...
It probably would work well as a weapon"
echo ""
