#!/bin/bash
#Monster Template

export monstHP=15 #monster's hit points
export monstDam=3 #monster's damage
export monstName='mimic' #monster's name
export monstDesc='I wish it was a chest' #monster's description
monstLoot=''
monstScroll=''
