#!/bin/bash

accHeal=3 #health increase
accDmg=0 #damage increase
accArm=4 #armor increase
accName='Brain Drain Helmet' #accesory name
accDesc='A helmet that drains brains. Hopefully your the brains of your enemies and not yours.' #armor description
