#!/bin/bash

accHeal=2 #health increase
accDmg=3 #damage increase
accArm=0 #armor increase
accName='sombrero' #accesory name
accDesc='An accessory said to contain the power of the legendary Estevez' #armor description
